#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/kubectld .
docker build -t ${REPO}/kubectld:${TAG} .

echo Built ${REPO}/kubectld:${TAG}
