#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}}
REPO=${REPO:-rancher}

cp ../bin/kubectld .

IMAGE=${REPO}/kubectld:${TAG}
docker build -t ${IMAGE} .
echo ${IMAGE} > ../dist/images
echo Built ${IMAGE}
